# 6. À l'aide des tableaux créés dans la question 3 ci-dessus, écrivez des commandes
NumPy pour ce qui suit :
a. Trouver la transposée de "ones" et "myarray2".
b. Trier leb. Trier le tableau "vowels" en ordre inverse. tableau "vowels" en ordre inverse.
c.Trier le tableau "myarray1" de manière à placer la plus petite valeur de la
colonne dans la première ligne, et ains de suite.

# A trouver le transposee de "ones" et "myarray2"

In [3]:
import numpy as np
#creer un tableau ones
ones = np.ones((3, 2))
#creer un tableau myarray2 
myarray2 = np.array([[2.7,-2,-19],[0,3.4,99.9],[10.6,0,13]])
#transposserles tableaux
ones_transposed = np.transpose(ones)
myarray2_transposed = np.transpose(myarray2)
print("Transposee de ones :\n", ones_transposed)
print("Transposee de myarray2 :\n", myarray2_transposed)

Transposee de ones :
 [[1. 1. 1.]
 [1. 1. 1.]]
Transposee de myarray2 :
 [[  2.7   0.   10.6]
 [ -2.    3.4   0. ]
 [-19.   99.9  13. ]]


# b. Trier le tableau "vowels" en ordre inverse.

In [5]:
#Definition du tableau vowels
vowels = ['a','e','i','o','u']
#option 1: Inverse l'ordre des elemsnts dans le tableau
vowels.reverse()
print("Tableau vowels inverse :", vowels)
#option 2: Trier le tableau dans l'ordre decroissant 
vowels_sorted_reverse = sorted(vowels , reverse=True)
print("Tableau vowels trie dans l' ordre inverse :", vowels_sorted_reverse)

Tableau vowels inverse : ['u', 'o', 'i', 'e', 'a']
Tableau vowels trie dans l' ordre inverse : ['u', 'o', 'i', 'e', 'a']


# c.Trier le tableau "myarray1" de manière à placer la plus petite valeur de la
colonne dans la première ligne, et ainsi de suite.

In [8]:
import numpy as np
#Definition du tableau myarray1
myarray1 = np.array([[2.7,-2,-19],[0,3.4,99.9],[10.6,0,13]])
#obtenir les indices des valeures triees pour chaque colonne
sorted_indices = np.argsort(myarray1, axis=0)
#Reorganiser les lignes des tableaux en fonction des indices tries
sorted_myarray1 = myarray1[sorted_indices[:, 0], :]
print("Tableau myarray1 trie avec la plus petite valeure de chaque colonne dans la premiere :\n",
    sorted_myarray1)

Tableau myarray1 trie avec la plus petite valeure de chaque colonne dans la premiere :
 [[  0.    3.4  99.9]
 [  2.7  -2.  -19. ]
 [ 10.6   0.   13. ]]


# 7. À l'aide des tableaux créés dans la question 4 ci-dessus, écrivez des commandes
NumPy pour ce qui suit :
a. Utilisez numpy.split() pour diviser le tableau "myarray2" en 5 tableaux.
Stockez vos tableaux résultants dans "myarray2A", "myarray2B",
"myarray2C", "myarray2D" et "myarray2E". Imprimez les tableaux
"myarray2A", "myarray2B", "myarray2C", "myarray2D" et "myarray2E".
b. Divisez le tableau "zeros" aux indices 2, 5, 7, 8 et stockez les tableaux
résultants dans "zerosA", "zerosB", "zerosC" et "zerosD". Imprimez-les.
c. Concaténer les tableaux "myarray2A", "myarray2B" et "myarray2C" en un
tableau ayant 3 lignes et 3 colonnes

# a. Utilisez numpy.split() pour diviser le tableau "myarray2" en 5 tableaux.
Stockez vos tableaux résultants dans "myarray2A", "myarray2B",
"myarray2C", "myarray2D" et "myarray2E". Imprimez les tableaux
"myarray2A", "myarray2B", "myarray2C", "myarray2D" et "myarray2E".

In [23]:
import numpy as np
#Diviser myarray2 en 5 parties
myarray2A, myarray2B, myarray2C, myarray2D, myarray2E = np.split(myarray2, 5)
#Imprimer les tableaux resultants
print("myarray2A:", myarray2A)
print("myarray2B:", myarray2B)
print("myarray2C:", myarray2C)
print("myarray2D:", myarray2D)
print("myarray2E:", myarray2E)

NameError: name 'myarray2' is not defined

# b. Divisez le tableau "zeros" aux indices 2, 5, 7, 8 et stockez les tableaux
résultants dans "zerosA", "zerosB", "zerosC" et "zerosD". Imprimez-les.

In [22]:
import numpy as np
#creer le tableau zeros 
zeros = np.zeros(10)
#Diviser zeros aux indices 2, 5, 7, 8
zerosA = zeros[:2+1]
zerosB = zeros[3:5+1]
zerosC = zeros[6:7+1]
zerosD = zeros[9:8:-1]
#Imprimer les tanleaux resultatants
print("zerosA :", zerosA)
print("zerosB :", zerosB)
print("zerosC :", zerosC)
print("zerosD :", zerosD)

zerosA : [0. 0. 0.]
zerosB : [0. 0. 0.]
zerosC : [0. 0.]
zerosD : [0.]


# c. Concaténer les tableaux "myarray2A", "myarray2B" et "myarray2C" en un
tableau ayant 3 lignes et 3 colonnes

In [21]:
import numpy as np
# Concatener des tableaux
concatener_array = np.concatener((myarray2A, myarray2B, myarray2C), axis=1)
# Redimensionnement le tableau concatener en 3 ligne et 3 colonnes
reshape_array = np.reshape(concatener_array,(3, 3))
print(reshape_array)


AttributeError: module 'numpy' has no attribute 'concatener'

# 8. Créez un tableau 2-D appelé "myarray4" en utilisant arange() ayant 14 lignes et 3
colonnes avec une valeur de départ de -1, un pas de 0.25. Divisez ce tableau en 3
parties égales et imprimez le résultat.

In [7]:
import numpy as np
#creer le tableau 2D avec arange()
myarray4 = np.arange(-1, 14*3*0.25-1,0.25).reshape((14, 3))
#Diviser le tableau en 3 parties egales
part_size = myarray4.shape[0] // 3
part1 = myarray4[:part_size]
part2 = myarray4[part_size:2*part_size]
part3 = myarray4[2*part_size:]
#Imprimer les resultats
print("Partie 1 :\n", part1)
print("Partie 2 :\n", part2)
print("Partie 3 :n\n", part3)

Partie 1 :
 [[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]]
Partie 2 :
 [[2.   2.25 2.5 ]
 [2.75 3.   3.25]
 [3.5  3.75 4.  ]
 [4.25 4.5  4.75]]
Partie 3 :n
 [[5.   5.25 5.5 ]
 [5.75 6.   6.25]
 [6.5  6.75 7.  ]
 [7.25 7.5  7.75]
 [8.   8.25 8.5 ]
 [8.75 9.   9.25]]


# 9. À l'aide du "myarray4" créé dans les questions précédentes, écrivez des commandes
pour ce qui suit :
a. Trouver la somme de tous les éléments.
b. Trouver la somme de tous les éléments par ligne

In [8]:
# Somme de tous les elements de myarray4
somme = sum(myarray4)
print("La somme de tous les elements dans myarray4 est :",somme)

La somme de tous les elements dans myarray4 est : [54.25 57.75 61.25]


In [9]:
#somme des elements par ligne dand myarray4
for ligne in myarray4:
    somme_ligne = sum(ligne)
print("La somme des elements dans la ligne est :", somme_ligne)

La somme des elements dans la ligne est : 27.0
